### ISSUE TITLE
Duplicate entries in auto completion window.

### ISSUE THREAD

**Issue by DasOhmoff** [coc-extensions/coc-omnisharp#17]
Hello, first of all, thank you for this awesome plugin, it is really great <3 .

I have a issue when auto completing with coc. Basically, coc shows multiple entries for the same item in the auto completion window (for example it shows multiple times the same member in the window).

For example:
![image](https://user-images.githubusercontent.com/16063186/77884740-f53e8500-7265-11ea-8803-09c20eba107c.png)

One of the entries is by your plugin (those that have the [LS]) at the end, how do I disable the ones that have the [OS] at the  end?)

**Comment by yatli** [comment]
A quick guess, "OS" means "omnisharp"?
If so, disable the `vim-omnisharp` plugin would do.

**Comment by DasOhmoff** [comment]
But don't I lose then all omnisharp features? Such as semantic highlighting and so on?
For example, with omnisharp-vim:
![image](https://user-images.githubusercontent.com/16063186/77886389-118ff100-7269-11ea-9511-40099af5812b.png)
with omnisharp-vim:
![image](https://user-images.githubusercontent.com/16063186/77886513-4f8d1500-7269-11ea-8aac-8e287736ad43.png)

I taught this plugin would use "vim-omnisharp" for auto completion? Is there no way to make them both work?

**Comment by yatli** [comment]
You can consult the omnisharp-vim manual for how to disable auto completion.
There's not much we can do from the language server side.

**Comment by DasOhmoff** [comment]
Ah ok, thanks.
