### ISSUE TITLE
Path to Omnisharp to prevent downloading

### ISSUE THREAD

**Issue by MarkusAmshove** [coc-extensions/coc-omnisharp#19]
Hello,

is it possible to configure the path to Omnisharp for this extension, so it doesn't try to download it?

I'm trying to use this behind a proxy which intercepts the download and therefore I can't start the extension :-/

For the VSCode extension there is a setting to define the path to Omnisharp.

**Comment by Philipp-M** [comment]
This should be fixed by https://github.com/coc-extensions/coc-omnisharp/pull/31
