### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by ErikFeeley** [coc-extensions/coc-omnisharp#2]
CocInfo

`## versions

vim version: NVIM v0.4.0-1256-g564d415d2
node version: v11.15.0
coc.nvim version: 0.0.72-22daa03a7d
term: xterm-kitty
platform: linux

## Messages
[coc.nvim] error: UnhandledRejection: Command "/home/erik/.config/coc/extensions/node_modules/coc-omnisharp/omnisharp/OmniSharp" of cs is not executable: Error: not found: /home/erik/.config/coc/extensions/node_modules/coc-omnisharp/omnisharp/OmniSharp
Error: Command "/home/erik/.config/coc/extensions/node_modules/coc-omnisharp/omnisharp/OmniSharp" of cs is not executable: Error: not found: /home/erik/.config/coc/extensions/node_modules/coc-omnisharp/omnisharp/OmniSharp
    at LanguageClient.createMessageTransports (/home/erik/.local/share/nvim/plugged/coc.nvim/build/index.js:65458:23)
## Output channel: highlight

[Info  - 9:14:05 AM] Highlight server running in node v11.15.0

## Output channel: cs

[Error  - 9:14:13 AM] Starting client failed: 
Error: Command "/home/erik/.config/coc/extensions/node_modules/coc-omnisharp/omnisharp/OmniSharp" of cs is not executable: Error: not found: /home/erik/.config/coc/extensions/node_modules/coc-omnisharp/omnisharp/OmniSharp
    at LanguageClient.createMessageTransports (/home/erik/.local/share/nvim/plugged/coc.nvim/build/index.js:65458:23)`

Steps taken.

1. Open neovim at project solution root
2. Open up a cs file in a project that is part of the solution

At first I thought it was a conflict due to not disabling the omnisharp server startup from vim-omnisharp. But I got the same error when configuring that to not start up its omnisharp server.

**Comment by yatli** [comment]
thanks,, I should chmod the unzipped executable

**Comment by mihaelartz** [comment]
@yatli OmniSharp.exe only exist

**Comment by yatli** [comment]
you mean, for Linux it's not a self-contained `dotnet` application?

**Comment by yatli** [comment]
please try v0.0.3

**Comment by mihaelartz** [comment]
@yatli now get new error: [coc.nvim] error: UnhandledRejection: Command "mono" of cs is not executable: Error: not found: mono

Mono is located in omnisharp/bin folder, start from there, and yes, first chmod

**Comment by mihaelartz** [comment]
@yatli this line: https://github.com/yatli/coc-omnisharp/blob/master/src/client/platform.ts#L76

change to: ```const omnisharpDirectory = path.join(__dirname, "..", "..", "omnisharp/omnisharp")```

and, mono must be installed manually via https://www.mono-project.com/download/stable/

after this changes, i don't get any errors, but completion is week, i don't get completions for class methods, attributes, namespaces...

**Comment by yatli** [comment]
@mihaelartz do you have `dotnet` installed? Maybe it will start the entry assembly just fine.

**Comment by yatli** [comment]
I guess I have to stop blind editing, and try to repro this problem

**Comment by yatli** [comment]
@mihaelartz what's the error when you try to run with the supplied `mono`?

**Comment by mihaelartz** [comment]
> do you have `dotnet` installed? Maybe it will start the entry assembly just fine.

Yes, i have installed dotnet.




> what's the error when you try to run with the supplied `mono`?

Command "mono" of cs is not executable: Error: not found: mono

**Comment by yatli** [comment]
pushed 0.0.4, please have a try.
It chmod & execute the script `run`.
I've tested on WSL and it works for me here.

**Comment by mihaelartz** [comment]
@yatli see my pull request

**Comment by yatli** [comment]
sorry for the trouble, some dumb mistakes..
please try 0.0.5

**Comment by yatli** [comment]
chmod timing is incorrect.
pushed 0.0.6

**Comment by mihaelartz** [comment]
@yatli i don't get any errors, but completion is very, very week

**Comment by mihaelartz** [comment]
![2019-07-14-131552_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/61182848-91bdea00-a639-11e9-8e6e-83a52339fe88.png)
![2019-07-14-131554_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/61182849-92568080-a639-11e9-90f6-659f482689f6.png)
![2019-07-14-131611_1680x1050_scrot](https://user-images.githubusercontent.com/29631158/61182851-92568080-a639-11e9-8e7e-42ea2cff6d19.png)

**Comment by yatli** [comment]
Yeah, it doesn't look like Omnisharp is helping a lot here

**Comment by yatli** [comment]
I got some exceptions in the log:

```
[Info  - 7:22:48 PM] Converting params for Request (1) textDocument/documentSymbol to OmniSharp.Extensions.LanguageServer.Protocol.Models.DocumentSymbolParams
[Error  - 7:22:48 PM] Failed to handle notification textDocument/documentSymbol - System.NullReferenceException: Object reference not set to an instance of an object
  at OmniSharp.LanguageServerProtocol.Handlers.DocumentSymbolHandler.Handle (OmniSharp.Extensions.LanguageServer.Protocol.Models.DocumentSymbolParams request, System.Threading.CancellationToken token) [0x00096] in <f545fd1de73a4d3082979fdff3bd0923>:0 
  at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2[TRequest,TResponse].Handle (TRequest request, System.Threading.CancellationToken cancellationToken, OmniSharp.Extensions.Embedded.MediatR.RequestHandlerDelegate`1[TResponse] next) [0x000e1] in <cdcdd2bceac34772b5fb2962192e6b77>:0 
  at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.RouteRequest (OmniSharp.Extensions.JsonRpc.IHandlerDescriptor descriptor, OmniSharp.Extensions.JsonRpc.Server.Request request) [0x002e2] in <cdcdd2bceac34772b5fb2962192e6b77>:0 
[Info  - 7:22:48 PM] Finished: Routing Request (1) textDocument/documentSymbol in 16ms
[Error  - 7:22:48 PM] Request textDocument/documentSymbol failed.
  Message: Internal Error - System.NullReferenceException: Object reference not set to an instance of an object
  at OmniSharp.LanguageServerProtocol.Handlers.DocumentSymbolHandler.Handle (OmniSharp.Extensions.LanguageServer.Protocol.Models.DocumentSymbolParams request, System.Threading.CancellationToken token) [0x00096] in <f545fd1de73a4d3082979fdff3bd0923>:0 
  at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2[TRequest,TResponse].Handle (TRequest request, System.Threading.CancellationToken cancellationToken, OmniSharp.Extensions.Embedded.MediatR.RequestHandlerDelegate`1[TResponse] next) [0x000e1] in <cdcdd2bceac34772b5fb2962192e6b77>:0 
  at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.RouteRequest (OmniSharp.Extensions.JsonRpc.IHandlerDescriptor descriptor, OmniSharp.Extensions.JsonRpc.Server.Request request) [0x002e2] in <cdcdd2bceac34772b5fb2962192e6b77>:0 
  Code: -32602 
```

**Comment by yatli** [comment]
CodeLens works, find reference works

**Comment by yatli** [comment]
hmm, autocompletion started to work after some time:

![image](https://user-images.githubusercontent.com/20684720/61182954-44f40680-a66d-11e9-845e-a165d5833f13.png)

**Comment by yatli** [comment]
well, not really. it's giving me wrong entries:

![image](https://user-images.githubusercontent.com/20684720/61182965-7ff63a00-a66d-11e9-8383-5893cdec2347.png)

**Comment by yatli** [comment]
Note, in the first screenshot the completion is correct, but the second one (Console) still displays the `Global` members.

**Comment by yatli** [comment]
@mihaelartz on Windows I had better luck with NetFX projects -- could you try change the target framework to something like `net46`?

**Comment by mihaelartz** [comment]
@yatli I do not know how to help, i'm new in .NET, I almost start to learn C#. In fact, I'm a Back-End Developer.

It would be good if omnisharp-vscode i adapt for coc.nvim (at least basic things).

**Comment by yatli** [comment]
@mihaelartz don't worry. You're helping a lot by testing it out :)

Please try 0.0.7 -- I've added an option to specify how to start omnisharp -- defaults to `dotnet` -- make sure you have dotnet core installed.

**Comment by ErikFeeley** [comment]
Hello @yatli I have just updated to 0.0.7 to give it another go!

I have a new issue now.

```
## versions

vim version: NVIM v0.4.0-1280-g47d53d66b
node version: v11.15.0
coc.nvim version: 0.0.73-226801ef28
term: xterm-kitty
platform: linux

## Messages

## Output channel: prettier


## Output channel: highlight

[Info  - 9:49:37 AM] Highlight server running in node v11.15.0

## Output channel: cs

A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/erik/.config/coc/extensions/node_modules/coc-omnisharp/omnisharp/omnisharp/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the /home/erik/.config/coc/extensions/node_modules/coc-omnisharp/omnisharp/omnisharp/OmniSharp.runtimeconfig.json file specifying the appropriate framework.
[Error  - 9:49:39 AM] dotnet exited with code: 131
[Info  - 9:49:39 AM] Connection to server got closed. Server will restart.
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/erik/.config/coc/extensions/node_modules/coc-omnisharp/omnisharp/omnisharp/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the /home/erik/.config/coc/extensions/node_modules/coc-omnisharp/omnisharp/omnisharp/OmniSharp.runtimeconfig.json file specifying the appropriate framework.
[Error  - 9:49:39 AM] dotnet exited with code: 131
[Info  - 9:49:39 AM] Connection to server got closed. Server will restart.
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/erik/.config/coc/extensions/node_modules/coc-omnisharp/omnisharp/omnisharp/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the /home/erik/.config/coc/extensions/node_modules/coc-omnisharp/omnisharp/omnisharp/OmniSharp.runtimeconfig.json file specifying the appropriate framework.
[Error  - 9:49:39 AM] dotnet exited with code: 131
[Info  - 9:49:39 AM] Connection to server got closed. Server will restart.
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/erik/.config/coc/extensions/node_modules/coc-omnisharp/omnisharp/omnisharp/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the /home/erik/.config/coc/extensions/node_modules/coc-omnisharp/omnisharp/omnisharp/OmniSharp.runtimeconfig.json file specifying the appropriate framework.
[Error  - 9:49:39 AM] dotnet exited with code: 131
[Info  - 9:49:39 AM] Connection to server got closed. Server will restart.
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/erik/.config/coc/extensions/node_modules/coc-omnisharp/omnisharp/omnisharp/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the /home/erik/.config/coc/extensions/node_modules/coc-omnisharp/omnisharp/omnisharp/OmniSharp.runtimeconfig.json file specifying the appropriate framework.
[Error  - 9:49:39 AM] Connection to server got closed. Server will not be restarted.
[Error  - 9:49:39 AM] dotnet exited with code: 131
```
And my output from `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:    7cecb35b92

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /opt/dotnet/sdk/2.2.105/

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.2.105 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.3 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
I am not using a global.json.

**Comment by Philipp-M** [comment]
I've got the same error as @ErikFeeley.

`dotnet --info` gives the same with the exception of `OS name: arch`:

Maybe something arch related (as manjaro is based on arch)?

**Comment by Admicos** [comment]
Same issue, on Arch

```
admicos ~ $ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.108
 Commit:    33ed5b90ce

Runtime Environment:
 OS Name:     arch
 OS Version:
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /opt/dotnet/sdk/2.2.108/

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.108 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.6 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

I was able to get to a different error by copying a `runtimeconfig.json` file from a hello world project's bin:

```
admicos ~/src/asd/bin/Debug/netcoreapp2.2 $ cp asd.runtimeconfig.json ~/.config/coc/extensions/node_modules/coc-omnisharp/omnisharp/omnisharp/OmniSharp.runtimeconfig.json
```

the second error is:

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.```

**Comment by yatli** [comment]
@ErikFeeley  @Philipp-M  @Admicos  @m5ome could you try 0.0.9? fixed some major problems. It's running snappy for me now :)

**Comment by ErikFeeley** [comment]
@yatli Definite improvement! I still have some local conflicts going on since I still have vim-omnisharp going on at the same time. But im definitely getting snappy completion from the language server!

**Comment by svermeulen** [comment]
Just chiming in to say that I've been trying to get it to work on macOS and having similar issues.  No errors but doesn't seem to help with suggestions out of the box.   When I set "useDotnet" to true, it helps a lot, but still gives me a lot of incorrect suggestions (looks like from the Global scope?).  I also noticed that if I force a write (`:w<cr>`) then try to open the suggestions again it works a lot better (but obviously that's not practical to do every time)

**Comment by yatli** [comment]
hi @svermeulen !
currently `useDotnet` is not yet ready -- `dotnet` is not aware that `Omnisharp` is built as a self-contained app with all the dependencies, and will fail to look them up.
When that happens, `coc-omnisharp` will appear to fail to start the language server, and effectively disabled.

I guess you have other completion plugins installed? If so, what you're seeing is the behavior of the other plugin.

**Comment by yatli** [comment]
closing for now.
