### ISSUE TITLE
using not working unless running  :e after opeining file

### ISSUE THREAD

**Issue by Laaman03** [coc-extensions/coc-omnisharp#33]
Just like the title says.
If I open the default Program.cs file that `dotnet new console` creates it throws errors all over the place because on `using System;` it says `The type or namespace 'Sytem' could not be found`
But I run `:e` in nvim and everything is good.
On Windows using dotnet core.

**Comment by yatli** [comment]
I'm slowly getting to understand the problem now -- the refs are not correctly added.
After https://github.com/OmniSharp/omnisharp-roslyn/pull/2002 we will be able to see detailed logs. I'll continue to hunt down the problem and hopefully fix it once and for all...

**Comment by yatli** [comment]
Fixed!
