### ISSUE TITLE
The type or namespace 'System' could not be found

### ISSUE THREAD

**Issue by JJJGGGG** [coc-extensions/coc-omnisharp#35]
Hi!
I just installed the coc-omnisharp extension. I opened an asp.net core file, and i have multiple errors because the linter cannot find some packages.
![image](https://user-images.githubusercontent.com/48324565/94371854-df543480-00cf-11eb-9ab8-f54dfbaf4c9a.png)
I didn't know if this applied for a bug, but does anyone have an idea of what is happening?

I can provide more info if needed.

EDIT:
OS: Manjaro Linux
Dotnet version: dotnet core 3.1.107

**Comment by emiliano-ruiz** [comment]
You can workaround this by editing the code a little or reloading with `:e`.
This should be marked as duplicate for #33 .

**Comment by yatli** [comment]
Thanks, I'll close this one as a dup.
