### ISSUE TITLE
The intellisense works well but no linting / no diagnostic shows

### ISSUE THREAD

**Issue by krehwell** [coc-extensions/coc-omnisharp#39]
The plugin used to work well in my machine. however I accidentally uninstalled the Omnishap-vim plugin for some debugging my vim config file. after a while I installed it back. everything's working fine except the linting does not shown anymore.

![image](https://user-images.githubusercontent.com/54220436/100187908-11ddaa80-2f24-11eb-9a79-f68180a2ff4c.png)

expected output: 
- there should be an indicator on the left most side to show the error I made

**Comment by yatli** [comment]
https://github.com/OmniSharp/omnisharp-roslyn/issues/2024#event-4032727761

Upstream is broken and fixed (again). Please wait until a new version is released and try again.

**Comment by krehwell** [comment]
alright, thanks. I'll just keep this open I guess till I get the latest update
