### ISSUE TITLE
omnisharp is not listed in CocList sources

### ISSUE THREAD

**Issue by edugomez102** [coc-extensions/coc-omnisharp#40]
When opening a .cs file omnisharp is not showed as a source although it is showed as installed in `:CocList extensions` and it appears to be started in the `:CocInfo` log.
This is happening in a windows 10 pc but i have another windows 10 pc and it worked with no problems just running `:CocInstall coc-omnisharp`.

I'm having no problems with other coc extensions for LSP, could this be related to my .NET version?

![image](https://user-images.githubusercontent.com/50159560/100276550-05784280-2f62-11eb-95e1-75e31c112b16.png)
![image](https://user-images.githubusercontent.com/50159560/100276613-19bc3f80-2f62-11eb-8ea8-02c38176c318.png)
![image](https://user-images.githubusercontent.com/50159560/100276739-4f612880-2f62-11eb-913f-2956ccbb29c9.png)

**Comment by eruizc-dev** [comment]
Something had to happen lately, my installation was working perfectly fine last week. This week I came back to work and I find omnisharp competition not working. I'm trying to figure out where the problem is, nice to know I'm not the only one.

**Comment by eruizc-dev** [comment]
In fact, downgrading omnisharp to [previous build](https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.37.3) makes it appear in sources and, in fact, it works.

![image](https://user-images.githubusercontent.com/58179604/100384245-7705ce80-2ffe-11eb-911f-2cd473543a98.png)

But I keep getting an error of an uncaught exception. I've seen this error before a couple times, but it was never as intense as this is. And I was never been able to replicate, it seemed like random but now it's always there after opening a `.cs` flile.

**Comment by eruizc-dev** [comment]
I've created #41 to allow you to specify which omnisharp version you want to download.

**Comment by edugomez102** [comment]
Nice but now when I run `:CocInstall https://github.com/coc-extensions/coc-omnisharp` I get this error:
 
![image](https://user-images.githubusercontent.com/50159560/100456102-1c34ab80-30c0-11eb-81ce-84db150ec629.png)

I'm not sure if that's the best way to install the extension but if i run just `CocInstall coc-omnisharp` it installs the version from [https://registry.npmjs.org/coc-omnisharp/-/coc-omnisharp-0.0.27.tar.gz](url) and it seems that version is not forked yet.

Notice that I'm using Windows 10.

**Comment by yatli** [comment]
@edugomez102 wait a sec I'll compile and publish it.

**Comment by yatli** [comment]
@edugomez102 0.0.28 is up now, just `:CocInstall coc-omnisharp`

**Comment by edugomez102** [comment]
Okay I've been able to install it now and by downloading an older version of the server my issue is solved, thanks!
