### ISSUE TITLE
Cannot make extension work - I think...

### ISSUE THREAD

**Issue by DasOhmoff** [coc-extensions/coc-omnisharp#43]
Hello, thank you for helping.
I am kind of confused on how to make this extension work.
I added the following lines of code into my `.vimrc`:
```
call plug#begin("~/vimfiles/plugged")
...
Plug 'coc-extensions/coc-omnisharp'     "<-- I think this should not even be here, I tested it with and without it being here
Plug 'neoclide/coc.nvim', {'branch': 'release'}
...
call plug#end()

let coc_global_extensions = ['coc-omnisharp']
```

I also used the command `:CocInstall coc-omnisharp` just to be on the save side.
The extension seems to be installed, here is the output of `CocList extensions`:
![image](https://user-images.githubusercontent.com/16063186/100546418-86d11d00-3261-11eb-85b8-f730831e3106.png)

But there is still no autocompletion and still no syntax highlighting.
If I install the [omnisharp-vim](https://github.com/OmniSharp/omnisharp-vim) plugin, then it works, but I would like to manage all language servers through coc.

Am I missing something here?
Do I have to set some language server settings like [here](https://github.com/neoclide/coc.nvim/wiki/Language-servers)?

**Comment by yatli** [comment]
The current latest version is (again) stalled because of upstream Omnisharp language server problems.
Please wait until a new upstream omnisharp-roslyn is released.

**Comment by DasOhmoff** [comment]
Ah ok.
Please tell me if you have time when it works again.

**Comment by yatli** [comment]
Roger roger. Will ping you on this thread.

**Comment by hyakki** [comment]
@yatli 

Do you have any ideas how long it generally takes ? As it's not the first time maybe you have an estimation for that ( or not ).
I will follow aswell the thread. Thanks for the hard work 🦾

**Comment by dilutedh2o** [comment]
Can I use an older version to get around this error for the time being?

**Comment by eruizc-dev** [comment]
> Can I use an older version to get around this error for the time being?

Open `:CocConfig` and set `omnisharp.version` to `v1.37.3` (or older)

```json
{
    "omnisharp.version": "v1.37.3"
}
```

Then delete the `coc-omnisharp-data` folder found in one of the next locations. Next time you open a `.cs` file it will download the specified version.

 - ~/.config/coc/extensions/coc-omnisharp-data/
 - ~/.coc/extensions/coc-omnisharp-data/
 - ~/AppData/Local/coc/extensions/coc-omnisharp-data

If it's not located in any of the above, you can run `:CocList extensions` and search for `coc-omnisharp` to get an idea where it could be located: It's always after `coc/extensions/`.

If the download instantly stops it's probably because you misspelled the version. It should be exactly as the title of any of [these releases](https://github.com/OmniSharp/omnisharp-roslyn/releases) or `latest`.

**Comment by dilutedh2o** [comment]
Thank you very much :bow:

**Comment by lubyrex** [comment]
Has anyone succeeded after doing the above steps to use an older omnisharp version? I've tried it on windows, and the download seems fine but nothing works when I go back to my editor. Am I missing something here?
Here are some relevant screenshots:
The package I downloaded:
![image](https://user-images.githubusercontent.com/16534505/101989172-8ca31580-3cd9-11eb-9b39-985011106287.png)
When I call "coc-definition" it says "definition provider not found" in the coc-log and nothing shows up in the Omnisharp language server output section
![image](https://user-images.githubusercontent.com/16534505/101989240-f1f70680-3cd9-11eb-8fd4-56e25112fef1.png)

Is there anything else I can do to debug this? Thanks!

**Comment by lubyrex** [comment]
> Has anyone succeeded after doing the above steps to use an older omnisharp version? I've tried it on windows, and the download seems fine but nothing works when I go back to my editor. Am I missing something here?
> Here are some relevant screenshots:
> The package I downloaded:
> ![image](https://user-images.githubusercontent.com/16534505/101989172-8ca31580-3cd9-11eb-9b39-985011106287.png)
> When I call "coc-definition" it says "definition provider not found" in the coc-log and nothing shows up in the Omnisharp language server output section
> ![image](https://user-images.githubusercontent.com/16534505/101989240-f1f70680-3cd9-11eb-8fd4-56e25112fef1.png)
> 
> Is there anything else I can do to debug this? Thanks!

So it looks like I've put `"omnisharp.debug.server": true` in my CocConfig, which has caused the server to not output anything. After removing it, the server worked flawlessly .
