### ISSUE TITLE
WSL2 + Unity setup

### ISSUE THREAD

**Issue by kalvinpearce** [coc-extensions/coc-omnisharp#55]
I have been using coc-omnisharp for Unity directly on a windows install of neovim and really enjoying the experience but I am having a lot of trouble getting it to work in WSL. Is it supported/possible to setup and if so any tips to get it working?

I am running a standard WSL2 - Ubuntu 20.04 setup. I have installed the preivew version of mono as it ships with msbuild now (finally 🙏 ) but can't seem to get any output from both `:CocInfo` and `:CocCommand workspace.showOutput` even with the `trace.server` and `debug.server` configs set like in the project README.

Any help would be greatly appreciated

**Comment by benyaminl** [comment]
@kalvinpearce Are you already install OmniSharp from https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.39.1 ? if not then please do install first, then add other configuration, last Time I use WSL2 Alpine, it works well as it should be, don't forget to set the OmniSharp path in the VimRC or in coc-settings.json
