### ISSUE TITLE
jsonrpc error on startup

### ISSUE THREAD

**Issue by ulyssesp** [coc-extensions/coc-omnisharp#6]
Error:
```
[coc.nvim] Error on load extension coc-omnisharp from C:\***\coc\extensions\node_modules\coc-omnisharp\out\client\extension.js: Error: Cannot find module 'vscode-jsonrpc'
```

Should vscode-jsonrpc be added to `package.json`?

**Comment by Kethku** [comment]
I can confirm, adding "vscode-jsonrpc": "^4.0.0" to the dependencies of the package.json and running npm install fixed the issue. I will create a PR

**Comment by yatli** [comment]
PR is merged and I think we can close this now.
