### ISSUE TITLE
Not working on MacOS

### ISSUE THREAD

**Issue by redjoker011** [coc-extensions/coc-omnisharp#64]
Hello after installing coc-omnisharp using CocInstall it seems that the extension cannot start due to `Unrecognized platform not supported` issue. I've already tried to restart Coc still the issue persists

Sharing my CocInfo
![Screen Shot 2021-09-29 at 12 00 27 AM](https://user-images.githubusercontent.com/22144212/135123758-73a6cfad-2400-4ac6-afe8-37f68912b7fa.png)

**Comment by more-pepsi** [comment]
I'm can't goto definition

```
[coc.nvim]: UnhandledRejection: Connection got disposed.
Error: Connection got disposed.
    at Object.dispose (/Users/bill/.vim/plugged/coc.nvim/build/index.js:61:4166)
    at Object.dispose (/Users/bill/.vim/plugged/coc.nvim/build/index.js:216:6222)

    at Timeout._onTimeout (/Users/bill/.vim/plugged/coc.nvim/build/index.js:221:6
522)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

**Comment by ywpkwon** [comment]
Hi @redjoker011, 
this might be out of the topic, but may I ask how to you colorize your `CocInfo`?

**Comment by redjoker011** [comment]
> Hi @redjoker011,
> this might be out of the topic, but may I ask how to you colorize your `CocInfo`?

Hi @ywpkwon  Im using this plugin https://github.com/lilydjwg/colorizer though its now a bit outdated but I'm sure still useful

**Comment by redjoker011** [comment]
Closing this issue

**Comment by hashcacher** [comment]
I'm having the same issue and would love to be able to use this extension.
