### ISSUE TITLE
TypeError: Cannot read property 'browser_download_url'

### ISSUE THREAD

**Issue by hananana** [coc-extensions/coc-omnisharp#8]
```
[coc.nvim] Error on active extension coc-omnisharp: TypeError: Cannot read property 'browser_download_url' of undefined
```

MacOS Mojave: 10.14.4
dotnet: 2.2.402
nvim: 0.3.4

Any other information?

**Comment by yatli** [comment]
could you try restarting vim?

**Comment by hananana** [comment]
already restarted.
already reinstalled coc.nvim&coc-omnisharp.
but same error occured.

**Comment by yatli** [comment]
seems like a problem fetching metadata from Github.
Could you try this in the browser: https://api.github.com/repos/omnisharp/omnisharp-roslyn/releases/latest and see if you can reach it?

**Comment by yatli** [comment]
ok I figured out. the package name changed from `omnisharp-osx-x64.zip` to `omnisharp-osx.zip`

**Comment by yatli** [comment]
try 0.0.20 now;

**Comment by hananana** [comment]
thanks!!

**Comment by 3rdey3** [comment]
having same problem on windows
nvim 0.4.3
